//! Targeted board generation for Practice mode.
//!
//! Each board is a position where the chosen technique is the **only** technique
//! that can make progress: it forces ≥1 cell, and no other technique forces
//! *anything* anywhere on the board. There may still be empty cells that are
//! currently unsolvable — that's fine; the drill only concerns the cells the
//! target unlocks.

use ohhi_core::bit_board::BitBoard;
use ohhi_core::board::Cell;
use ohhi_solver::structs::{Technique, TechniqueSet};
use ohhi_solver::v1::deduction::forced_once;
use crate::full::og::OgGenerator;
use crate::FullBoardGenerator;
use rand::seq::SliceRandom;
use rand::{Rng, RngExt};

/// Which technique a practice board drills.
#[derive(Copy, Clone, PartialEq, Eq, Debug, Hash, serde::Serialize, serde::Deserialize)]
pub enum Target {
    PairExtension,
    GapFill,
    Saturation,
    TwinCompletion,
    /// Reserved — generated by embedding mined counting atoms (not in the MVP).
    Counting,
}

impl Target {
    fn technique(self) -> Option<Technique> {
        match self {
            Target::PairExtension => Some(Technique::PairExtension),
            Target::GapFill => Some(Technique::GapFill),
            Target::Saturation => Some(Technique::Saturation),
            Target::TwinCompletion => Some(Technique::TwinCompletion),
            Target::Counting => None, // deferred
        }
    }

    /// Keep-probability window when digging — twin needs near-complete lines, the
    /// simpler line techniques want more open structure.
    fn keep_range(self) -> (f64, f64) {
        match self {
            Target::TwinCompletion => (0.80, 0.95),
            Target::Saturation => (0.55, 0.85),
            _ => (0.45, 0.80),
        }
    }
}

/// A single practice position. `given` is the board shown (locked cells), the
/// remaining cells are to be deduced; `solution` is the unique-enough completion
/// the givens came from.
#[derive(Clone, Debug)]
pub struct PracticeBoard {
    pub given: BitBoard,
    pub solution: BitBoard,
    pub target: Target,
}

/// All cells the target technique forces on `board` right now, with their colour.
pub fn target_forced(board: &BitBoard, target: Target) -> Vec<((usize, usize), Cell)> {
    let Some(t) = target.technique() else { return vec![] };
    forced_once(board, TechniqueSet::NONE.with(t))
        .into_iter()
        .map(|(r, c, cell, _)| ((r, c), cell))
        .collect()
}

/// Generates a board drilling `target`, or `None` within `tries`.
///
/// Accept iff the target forces ≥1 cell **and no other technique forces
/// anything** — the only available progress is via the target technique.
/// `TwinCompletion` uses a constructive generator (random dig finds such boards
/// roughly 1 in 200 000); the line techniques use random digging.
pub fn targeted_board(
    target: Target,
    n: usize,
    rng: &mut impl Rng,
    tries: usize,
) -> Option<PracticeBoard> {
    let t = target.technique()?; // Counting not yet supported
    if t == Technique::TwinCompletion {
        return construct_twin(n, rng, tries);
    }
    let others = TechniqueSet::ALL.without(t);
    let (lo, hi) = target.keep_range();

    for _ in 0..tries {
        let solution = OgGenerator.generate(n, rng);
        let keep = rng.random_range(lo..hi);
        let board = dig(&solution, keep, rng);

        if forced_once(&board, TechniqueSet::NONE.with(t)).is_empty() {
            continue; // target must fire
        }
        if forced_once(&board, others).is_empty() {
            // ...and nothing else may.
            return Some(PracticeBoard { given: board, solution, target });
        }
    }
    None
}

/// Returns a copy of `solution` with each cell independently kept with
/// probability `keep`, the rest blanked.
fn dig(solution: &BitBoard, keep: f64, rng: &mut impl Rng) -> BitBoard {
    let mut board = BitBoard::new(solution.width(), solution.height());
    for r in 0..solution.height() {
        for c in 0..solution.width() {
            if rng.random_bool(keep) {
                board.set((r, c), solution.get((r, c)));
            }
        }
    }
    board
}

/// True iff the target technique fires and **no** other technique forces anything.
fn only_twin_fires(board: &BitBoard) -> bool {
    let others = TechniqueSet::ALL.without(Technique::TwinCompletion);
    !forced_once(board, TechniqueSet::NONE.with(Technique::TwinCompletion)).is_empty()
        && forced_once(board, others).is_empty()
}

/// Constructs a twin-completion board: a completed row `r2` plus a near-twin row
/// `r` that differs from it in exactly two cells (left empty), with every other
/// trigger blanked away. Then greedily fills cells back while the "only twin
/// fires" invariant holds, for a fuller board.
fn construct_twin(n: usize, rng: &mut impl Rng, tries: usize) -> Option<PracticeBoard> {
    for _ in 0..tries {
        let solution = OgGenerator.generate(n, rng);

        // Candidate row pairs (r, r2) ≥3 apart differing in exactly 2 columns.
        let mut pairs: Vec<(usize, usize, usize, usize)> = Vec::new();
        for r in 0..n {
            for r2 in 0..n {
                if r2.abs_diff(r) < 3 { continue; }
                let diffs: Vec<usize> = (0..n)
                    .filter(|&c| solution.get((r, c)) != solution.get((r2, c)))
                    .collect();
                if diffs.len() == 2 {
                    pairs.push((r, r2, diffs[0], diffs[1]));
                }
            }
        }
        pairs.shuffle(rng);

        for (r, r2, e1, e2) in pairs {
            // Minimal board: full row r2, row r minus its two differing cells.
            let mut board = BitBoard::new(n, n);
            for c in 0..n {
                board.set((r2, c), solution.get((r2, c)));
                if c != e1 && c != e2 {
                    board.set((r, c), solution.get((r, c)));
                }
            }
            if !only_twin_fires(&board) {
                continue;
            }
            // Greedily fill other cells back while the invariant survives.
            let mut rest: Vec<(usize, usize)> = (0..n)
                .flat_map(|rr| (0..n).map(move |cc| (rr, cc)))
                .filter(|&(rr, _)| rr != r && rr != r2)
                .collect();
            rest.shuffle(rng);
            for (rr, cc) in rest {
                board.set((rr, cc), solution.get((rr, cc)));
                if !only_twin_fires(&board) {
                    board.set((rr, cc), Cell::Nothing); // revert
                }
            }
            return Some(PracticeBoard { given: board, solution, target: Target::TwinCompletion });
        }
    }
    None
}
